### ISSUE TITLE
Undefined index: token

### ISSUE THREAD

**Issue by brandy** [formr/Formr#34]
Whenever I try to submit my form I get the following error

```
Undefined index: token

#0 lib/formr/class.formr.php(283): Core\Error::errorHandler()
#1 App/Controllers/AuthController.php(121): Formr->submit()
```

Controller File
```
 $form = new \Formr('bootstrap');

if ($form->submit()) {
}
```

View File 
```
{!! $form->form_open('', 'loginForm', Site::url('login'), 'post', 'class="form"') !!}

                {!! $form->csrf() !!}

                <div class="form-fields-split">
                    {!! $form->input_text('username', 'Username <span>*</span>') !!}
                    {!! $form->input_password('password', 'Password <span>*</span>') !!}
                </div>

                <button type="submit" class="g-recaptcha" data-sitekey="{{ env('RECAPTCHA_KEY') }}" data-callback='onSubmit'>Login</button>

                {!! $form->form_close() !!}
```

**Comment by timgavin** [comment]
Wy don't you use Laravel's form handling? Formr isn't meant for that.
